FROM node:18-alpine as builder
WORKDIR /app
COPY package.json .

# Add this line to accept the environment variable
ARG REACT_APP_API_URL 

RUN npm install
COPY . .

# Pass the environment variable to your build command (if needed)
RUN npm run build --REACT_APP_API_URL=$REACT_APP_API_URL 

FROM nginx
COPY --from=builder /app/build /usr/share/nginx/html
